# Generated by Django 3.1.1 on 2020-09-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(default='c2a0676af5', editable=False, max_length=10),
        ),
    ]
