# Generated by Django 3.1.1 on 2020-09-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200922_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(default='7205307aa8', editable=False, max_length=10),
        ),
    ]
