# Generated by Django 3.1.1 on 2020-09-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200925_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(default='a6a19e58fe', editable=False, max_length=10),
        ),
    ]
