# Generated by Django 3.1.1 on 2020-09-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='mobile',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
