# Generated by Django 3.1.1 on 2020-09-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200922_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('deliver', 'Delivered'), ('Pending', 'Pending'), ('On Way', 'On the Way'), ('Canceled', 'Canceled')], default='Pending', max_length=10),
        ),
    ]
